nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.6.1.cjs

checksumBehavior: 'update'
supportedArchitectures:
    cpu:
        - x64
        - arm64
    libc:
        - glibc
        - musl
    os:
        - darwin
        - linux
