name: web-service

on:
    push:
        branches: [main]
        paths:
            - 'services/user/**'
            - 'packages/**'
            - 'package.json'
            - '*.lock'
            - '.yarnrc.yml'
            - 'tsconfig.base.json'
            - '.prettier*'
            - '.github/**'

    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - 'services/user/**'
            - 'packages/**'
            - 'package.json'
            - '*.lock'
            - '.yarnrc.yml'
            - 'tsconfig.base.json'
            - '.prettier*'
            - '.github/**'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    template-ci:
        name: web-service
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - name: Install Dependencies
              run: yarn install --immutable --immutable-cache

            - name: Build User Service
              run: yarn workspace @service/user build
